name: Publish Docker Image
on: [push]
jobs:
  publish:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: docker build -t cboulanger/docker-phpfarm:latest .
      - name: Test
        run: ./test.sh
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: cboulanger/docker-phpfarm
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
